"""Initial schema.

Revision ID: 0b8d73696951
Revises:
Create Date: 2026-01-19 00:51:16.143761+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b8d73696951"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("dba_names", sa.Text(), nullable=True),
        sa.Column("ein", sa.String(length=20), nullable=True),
        sa.Column(
            "entity_type",
            sa.Enum(
                "LLC",
                "CORPORATION",
                "S_CORPORATION",
                "PARTNERSHIP",
                "SOLE_PROPRIETORSHIP",
                "TRUST",
                "NON_PROFIT",
                "OTHER",
                name="entity_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("formation_state", sa.String(length=2), nullable=True),
        sa.Column("formation_date", sa.Date(), nullable=True),
        sa.Column("fiscal_year_end", sa.String(length=5), nullable=True),
        sa.Column("business_address", sa.String(length=255), nullable=True),
        sa.Column("business_city", sa.String(length=100), nullable=True),
        sa.Column("business_state", sa.String(length=2), nullable=True),
        sa.Column("business_zip", sa.String(length=10), nullable=True),
        sa.Column("mailing_address", sa.String(length=255), nullable=True),
        sa.Column("mailing_city", sa.String(length=100), nullable=True),
        sa.Column("mailing_state", sa.String(length=2), nullable=True),
        sa.Column("mailing_zip", sa.String(length=10), nullable=True),
        sa.Column("accounting_record_id", sa.String(length=100), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entities_accounting_record_id"),
        "entities",
        ["accounting_record_id"],
        unique=False,
    )
    op.create_index(op.f("ix_entities_ein"), "entities", ["ein"], unique=True)
    op.create_index(
        op.f("ix_entities_legal_name"), "entities", ["legal_name"], unique=False
    )
    op.create_table(
        "bank_accounts",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("bank_name", sa.String(length=255), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=True),
        sa.Column(
            "account_type",
            sa.Enum(
                "CHECKING",
                "SAVINGS",
                "MONEY_MARKET",
                "CD",
                "BUSINESS_CHECKING",
                "BUSINESS_SAVINGS",
                "MERCHANT_ACCOUNT",
                "PAYROLL",
                "OTHER",
                name="account_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("account_number_last4", sa.String(length=4), nullable=True),
        sa.Column("routing_number", sa.String(length=9), nullable=True),
        sa.Column("account_nickname", sa.String(length=100), nullable=True),
        sa.Column("opened_date", sa.Date(), nullable=True),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("primary_contact", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("branch_address", sa.Text(), nullable=True),
        sa.Column("online_banking_url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bank_accounts_entity_id"), "bank_accounts", ["entity_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "ARTICLES_OF_ORGANIZATION",
                "ARTICLES_OF_INCORPORATION",
                "CERTIFICATE_OF_FORMATION",
                "OPERATING_AGREEMENT",
                "BYLAWS",
                "PARTNERSHIP_AGREEMENT",
                "MEETING_MINUTES",
                "ANNUAL_MEETING",
                "SPECIAL_MEETING",
                "WRITTEN_CONSENT",
                "ANNUAL_REPORT",
                "AMENDMENT",
                "STATEMENT_OF_INFORMATION",
                "CERTIFICATE_OF_GOOD_STANDING",
                "FOREIGN_QUALIFICATION",
                "EIN_LETTER",
                "TAX_RETURN",
                "TAX_ELECTION",
                "BANK_RESOLUTION",
                "SIGNATURE_CARD",
                "CONTRACT",
                "LEASE",
                "INSURANCE_POLICY",
                "MEMBERSHIP_CERTIFICATE",
                "STOCK_CERTIFICATE",
                "TRANSFER_AGREEMENT",
                "CORRESPONDENCE",
                "OTHER",
                name="document_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("version", sa.String(length=20), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_confidential", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documents_entity_id"), "documents", ["entity_id"], unique=False
    )
    op.create_index(op.f("ix_documents_title"), "documents", ["title"], unique=False)
    op.create_table(
        "entity_relationships",
        sa.Column("parent_entity_id", sa.UUID(), nullable=False),
        sa.Column("child_entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "PARENT_SUBSIDIARY",
                "HOLDING_COMPANY",
                "MEMBER",
                "MANAGER",
                "JOINT_VENTURE",
                "AFFILIATE",
                "SERIES",
                "DISREGARDED_ENTITY",
                "OTHER",
                name="relationship_type_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "ownership_percentage", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["child_entity_id"], ["entities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_entity_id"], ["entities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_entity_id",
            "child_entity_id",
            "relationship_type",
            name="uq_entity_relationship",
        ),
    )
    op.create_index(
        op.f("ix_entity_relationships_child_entity_id"),
        "entity_relationships",
        ["child_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_relationships_parent_entity_id"),
        "entity_relationships",
        ["parent_entity_id"],
        unique=False,
    )
    op.create_table(
        "owners",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("owner_name", sa.String(length=255), nullable=False),
        sa.Column("owner_entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "ownership_type",
            sa.Enum(
                "MEMBER",
                "MANAGING_MEMBER",
                "SHAREHOLDER",
                "GENERAL_PARTNER",
                "LIMITED_PARTNER",
                "BENEFICIARY",
                "TRUSTEE",
                "DIRECTOR",
                "OFFICER",
                name="ownership_type_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "ownership_percentage", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "capital_contribution", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "profit_share_percentage", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "loss_share_percentage", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("voting_percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("ein_or_ssn", sa.String(length=20), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["owner_entity_id"], ["entities.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_owners_entity_id"), "owners", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_owners_owner_entity_id"), "owners", ["owner_entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_owners_owner_name"), "owners", ["owner_name"], unique=False
    )
    op.create_table(
        "registered_agents",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("agent_name", sa.String(length=255), nullable=False),
        sa.Column("agent_company", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state_address", sa.String(length=2), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("renewal_date", sa.Date(), nullable=True),
        sa.Column("annual_cost", sa.String(length=50), nullable=True),
        sa.Column("account_number", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "state", "is_active", name="uq_entity_state_active_agent"
        ),
    )
    op.create_index(
        op.f("ix_registered_agents_entity_id"),
        "registered_agents",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registered_agents_state"), "registered_agents", ["state"], unique=False
    )
    op.create_table(
        "state_registrations",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column(
            "registration_type",
            sa.Enum(
                "DOMESTIC",
                "FOREIGN",
                "ASSUMED_NAME",
                "PROFESSIONAL",
                "SPECIALTY",
                name="registration_type_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PENDING",
                "EXPIRED",
                "WITHDRAWN",
                "REVOKED",
                "SUSPENDED",
                "REINSTATED",
                name="registration_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("file_number", sa.String(length=50), nullable=True),
        sa.Column("registered_name", sa.String(length=255), nullable=True),
        sa.Column("registration_date", sa.Date(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("annual_report_due", sa.Date(), nullable=True),
        sa.Column("last_annual_report", sa.Date(), nullable=True),
        sa.Column("next_renewal_date", sa.Date(), nullable=True),
        sa.Column("filing_fee", sa.String(length=50), nullable=True),
        sa.Column("annual_fee", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_good_standing", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "state", "registration_type", name="uq_entity_state_type"
        ),
    )
    op.create_index(
        op.f("ix_state_registrations_entity_id"),
        "state_registrations",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_state_registrations_file_number"),
        "state_registrations",
        ["file_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_state_registrations_state"),
        "state_registrations",
        ["state"],
        unique=False,
    )
    op.create_table(
        "tax_filings",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "filing_type",
            sa.Enum(
                "FEDERAL_INCOME",
                "STATE_INCOME",
                "FRANCHISE_TAX",
                "SALES_TAX",
                "PAYROLL_TAX",
                "PROPERTY_TAX",
                "ESTIMATED_TAX",
                "ANNUAL_REPORT",
                "K1",
                "OTHER",
                name="tax_filing_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("jurisdiction", sa.String(length=50), nullable=False),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column("tax_period", sa.String(length=20), nullable=True),
        sa.Column(
            "frequency",
            sa.Enum(
                "ANNUAL",
                "QUARTERLY",
                "MONTHLY",
                "SEMI_ANNUAL",
                "ONE_TIME",
                name="filing_frequency_enum",
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("extended_due_date", sa.Date(), nullable=True),
        sa.Column("filed_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "FILED",
                "EXTENDED",
                "LATE",
                "NOT_REQUIRED",
                name="filing_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("form_number", sa.String(length=50), nullable=True),
        sa.Column("confirmation_number", sa.String(length=100), nullable=True),
        sa.Column("preparer", sa.String(length=255), nullable=True),
        sa.Column("amount_due", sa.String(length=50), nullable=True),
        sa.Column("amount_paid", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tax_filings_due_date"), "tax_filings", ["due_date"], unique=False
    )
    op.create_index(
        op.f("ix_tax_filings_entity_id"), "tax_filings", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_tax_filings_jurisdiction"),
        "tax_filings",
        ["jurisdiction"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tax_filings_tax_year"), "tax_filings", ["tax_year"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tax_filings_tax_year"), table_name="tax_filings")
    op.drop_index(op.f("ix_tax_filings_jurisdiction"), table_name="tax_filings")
    op.drop_index(op.f("ix_tax_filings_entity_id"), table_name="tax_filings")
    op.drop_index(op.f("ix_tax_filings_due_date"), table_name="tax_filings")
    op.drop_table("tax_filings")
    op.drop_index(
        op.f("ix_state_registrations_state"), table_name="state_registrations"
    )
    op.drop_index(
        op.f("ix_state_registrations_file_number"), table_name="state_registrations"
    )
    op.drop_index(
        op.f("ix_state_registrations_entity_id"), table_name="state_registrations"
    )
    op.drop_table("state_registrations")
    op.drop_index(op.f("ix_registered_agents_state"), table_name="registered_agents")
    op.drop_index(
        op.f("ix_registered_agents_entity_id"), table_name="registered_agents"
    )
    op.drop_table("registered_agents")
    op.drop_index(op.f("ix_owners_owner_name"), table_name="owners")
    op.drop_index(op.f("ix_owners_owner_entity_id"), table_name="owners")
    op.drop_index(op.f("ix_owners_entity_id"), table_name="owners")
    op.drop_table("owners")
    op.drop_index(
        op.f("ix_entity_relationships_parent_entity_id"),
        table_name="entity_relationships",
    )
    op.drop_index(
        op.f("ix_entity_relationships_child_entity_id"),
        table_name="entity_relationships",
    )
    op.drop_table("entity_relationships")
    op.drop_index(op.f("ix_documents_title"), table_name="documents")
    op.drop_index(op.f("ix_documents_entity_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_bank_accounts_entity_id"), table_name="bank_accounts")
    op.drop_table("bank_accounts")
    op.drop_index(op.f("ix_entities_legal_name"), table_name="entities")
    op.drop_index(op.f("ix_entities_ein"), table_name="entities")
    op.drop_index(op.f("ix_entities_accounting_record_id"), table_name="entities")
    op.drop_table("entities")
    # ### end Alembic commands ###
